-- MySQL Script generated by MySQL Workbench
-- 12/28/16 11:43:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fond_de_placard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fond_de_placard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fond_de_placard` DEFAULT CHARACTER SET utf8 ;
USE `fond_de_placard` ;

-- -----------------------------------------------------
-- Table `fond_de_placard`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fond_de_placard`.`ingredients` (
  `ing_id` INT NOT NULL AUTO_INCREMENT,
  `ing_name` VARCHAR(45) NOT NULL,
  `ing_valide` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ing_id`),
  UNIQUE INDEX `ing_name_UNIQUE` (`ing_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fond_de_placard`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fond_de_placard`.`picture` (
  `pic_id` INT NOT NULL AUTO_INCREMENT,
  `pic_name` NVARCHAR(255) NOT NULL,
  `pic_type` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`pic_id`),
  UNIQUE INDEX `img_name_UNIQUE` (`pic_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fond_de_placard`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fond_de_placard`.`recipe` (
  `rec_id` INT NOT NULL AUTO_INCREMENT,
  `rec_name` VARCHAR(255) NOT NULL,
  `rec_html` TEXT NOT NULL,
  `rec_type` VARCHAR(45) NOT NULL,
  `picture_pic_id` INT NOT NULL,
  `rec_valide` TINYINT(1) NOT NULL,
  PRIMARY KEY (`rec_id`, `picture_pic_id`),
  UNIQUE INDEX `rec_name_UNIQUE` (`rec_name` ASC),
  INDEX `fk_recipe_picture1_idx` (`picture_pic_id` ASC),
  CONSTRAINT `fk_recipe_picture1`
    FOREIGN KEY (`picture_pic_id`)
    REFERENCES `fond_de_placard`.`picture` (`pic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fond_de_placard`.`link_ing_rec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fond_de_placard`.`link_ing_rec` (
  `ingredients_ing_id` INT NOT NULL,
  `recipe_rec_id` INT NOT NULL,
  PRIMARY KEY (`ingredients_ing_id`, `recipe_rec_id`),
  INDEX `fk_ingredients_has_recipe_recipe1_idx` (`recipe_rec_id` ASC),
  INDEX `fk_ingredients_has_recipe_ingredients_idx` (`ingredients_ing_id` ASC),
  CONSTRAINT `fk_ingredients_has_recipe_ingredients`
    FOREIGN KEY (`ingredients_ing_id`)
    REFERENCES `fond_de_placard`.`ingredients` (`ing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredients_has_recipe_recipe1`
    FOREIGN KEY (`recipe_rec_id`)
    REFERENCES `fond_de_placard`.`recipe` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fond_de_placard`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fond_de_placard`.`group` (
  `gro_id` INT NOT NULL AUTO_INCREMENT,
  `gro_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gro_id`),
  UNIQUE INDEX `gro_name_UNIQUE` (`gro_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fond_de_placard`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fond_de_placard`.`user` (
  `use_id` INT NOT NULL AUTO_INCREMENT,
  `use_pseudo` VARCHAR(45) NOT NULL,
  `use_email` VARCHAR(45) NOT NULL,
  `use_password` VARCHAR(45) NOT NULL,
  `group_gro_id` INT NOT NULL,
  PRIMARY KEY (`use_id`, `group_gro_id`),
  UNIQUE INDEX `use_pseudo_UNIQUE` (`use_pseudo` ASC),
  UNIQUE INDEX `use_email_UNIQUE` (`use_email` ASC),
  INDEX `fk_user_group1_idx` (`group_gro_id` ASC),
  CONSTRAINT `fk_user_group1`
    FOREIGN KEY (`group_gro_id`)
    REFERENCES `fond_de_placard`.`group` (`gro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fond_de_placard`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fond_de_placard`.`comment` (
  `com_id` INT NOT NULL AUTO_INCREMENT,
  `recipe_rec_id` INT NOT NULL,
  `user_use_id` INT NOT NULL,
  `com_content` TEXT NULL,
  `com_fav` TINYINT(1) NULL,
  `com_date` DATETIME NULL,
  PRIMARY KEY (`com_id`, `recipe_rec_id`, `user_use_id`),
  INDEX `fk_comment_recipe1_idx` (`recipe_rec_id` ASC),
  INDEX `fk_comment_user1_idx` (`user_use_id` ASC),
  CONSTRAINT `fk_comment_recipe1`
    FOREIGN KEY (`recipe_rec_id`)
    REFERENCES `fond_de_placard`.`recipe` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_use_id`)
    REFERENCES `fond_de_placard`.`user` (`use_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fond_de_placard`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fond_de_placard`.`theme` (
  `the_id` INT NOT NULL AUTO_INCREMENT,
  `the_name` VARCHAR(45) NOT NULL,
  `the_valide` TINYINT(1) NOT NULL,
  PRIMARY KEY (`the_id`),
  UNIQUE INDEX `the_name_UNIQUE` (`the_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fond_de_placard`.`link_rec_the`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fond_de_placard`.`link_rec_the` (
  `recipe_rec_id` INT NOT NULL,
  `theme_the_id` INT NOT NULL,
  PRIMARY KEY (`recipe_rec_id`, `theme_the_id`),
  INDEX `fk_recipe_has_theme_theme1_idx` (`theme_the_id` ASC),
  INDEX `fk_recipe_has_theme_recipe1_idx` (`recipe_rec_id` ASC),
  CONSTRAINT `fk_recipe_has_theme_recipe1`
    FOREIGN KEY (`recipe_rec_id`)
    REFERENCES `fond_de_placard`.`recipe` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_has_theme_theme1`
    FOREIGN KEY (`theme_the_id`)
    REFERENCES `fond_de_placard`.`theme` (`the_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
